apiVersion: v1
kind: ConfigMap
metadata:
  name: kasandra-chumpitaz-configmap
  namespace: kasandra-chumpitaz-namespace
data:
  app-config: "activo"
  DATABASE_URL: "r2dbc:postgresql://ep-icy-sunset-a578ej1o.us-east-2.aws.neon.tech/shed?sslmode=require"
  DATABASE_USERNAME: "shed_owner"
  DATABASE_PASSWORD: "LtCjN8zZmUa1"
  feature-x-enabled: "true"